### ISSUE TITLE
[Review/Raehan] 코드 공유 감사합니다!

### ISSUE THREAD

**Issue by rae-han** [overscrap/nextjs-challenge-newyorktimes#1]
코드 공유해주셔서 감사합니다! 
궁금한게 있는데 대부분 css-module 을 선택하셨던데 styled-js를 선택하셨더라고요.
혹시 사용하신 이유가 있으신지, 사용하시면서 어떤 점이 좋았고 불편했는지 공유해주시면 감사합니다.
사실 저도 아무 생각 없이 제 편의를 위해 css-module를 사용해서 궁금했습니다!!
감사합니다!

**Comment by overscrap** [comment]
코드리뷰감사합니다.

사실 style.jsx를 사용한 이유는 딱히 없습니다.

module.css는 자주 써봤던 방식이라서 새로 배운 기술은 어떤 특징이 있는지 그냥 써봤습니다. 

개인적으로 파일 하나에 html, css, js 몽땅 들어가있는것을 좋아하지 않다보니 차후에는 module.css방식을 주로 사용할 것 같습니다.

**Comment by rae-han** [comment]
@overscrap 감사합니다. 답변이 도움 됐습니다!!
